services:
  postgres:
    image: postgres:16-alpine
    container_name: date2gether-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: date2gether
      POSTGRES_PASSWORD: date2gether
      POSTGRES_DB: date2gether
    ports:
      - '5432:5432'
    volumes:
      - date2gether_postgres_data:/var/lib/postgresql/data

volumes:
  date2gether_postgres_data:
